volumes:
  esdata1:
    driver: local

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.3
    ports:
      - "12201:12201/udp"
    volumes:
      - ./armagetron/logstash/pipeline:/usr/share/logstash/pipeline:ro
    depends_on:
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  
  tron_pub:
    image: codefossa/armagetronad:latest
    container_name: TRON_PUB
    ports:
      - "4534:4534/udp"
    depends_on:
      - logstash
    volumes:
      - ./armagetron/syn_uk_settings/pub:/app/server/server
    restart: unless-stopped
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "tron"

  tron_tst:
    image: codefossa/armagetronad:latest
    container_name: TRON_TST
    ports:
      - "4535:4535/udp"
    depends_on:
      - logstash
    volumes:
      - ./armagetron/syn_uk_settings/tst:/app/server/server
    restart: unless-stopped
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "tron"
    

  watcher:
    build: 
      context: armagetron/watcher/.
      dockerfile: Dockerfile
    container_name: watcher
    depends_on:
      - logstash
      - postgres
    volumes:
      - ./armagetron/syn_uk_settings:/settings
      - ./armagetron/watcher:/app
      - /app/node_modules
    environment:
      AUTH_SERVER_URL: ${AUTH_SERVER_URL}
    command: npm run dev

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "7432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: unless-stopped
