services:
  
  tron_pub:
    image: codefossa/armagetronad:latest
    container_name: TRON_PUB
    ports:
      - "4534:4534/udp"
    volumes:
      - ./armagetron/syn_uk_settings/pub:/app/server/server
    restart: unless-stopped

  tron_tst:
    image: codefossa/armagetronad:latest
    container_name: TRON_TST
    ports:
      - "4535:4535/udp"
    volumes:
      - ./armagetron/syn_uk_settings/tst:/app/server/server
    restart: unless-stopped
    

  watcher:
    build: 
      context: armagetron/watcher/.
      dockerfile: Dockerfile
    container_name: watcher
    depends_on:
      - postgres
    volumes:
      - ./armagetron/syn_uk_settings:/settings
      - ./armagetron/watcher:/app
      - /app/node_modules
    environment:
      AUTH_SERVER_URL: ${AUTH_SERVER_URL}
    command: npm run dev

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "7432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: unless-stopped
